apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smith987-poi-map-app-dev
  annotations:
    argocd/app-name: smith987-poi-map-app-dev
    backstage.io/kubernetes-id: smith987-poi-map-app
    backstage.io/kubernetes-namespace: smith987
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/smith987-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/smith987/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/smith987/deployments/smith987-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/smith987-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://smith987-poi-map-app-smith987.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/smith987"
  system: workshop-system-smith987
  consumesApis:
    - gateway-api-smith987
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-smith987
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/smith987"
